language: node_js

node_js:
  - "4.1"

before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

script:
 - npm run lint
 - npm run build
 - npm test

branches:
  only:
    - gh-pages